project:
  type: website
  output-dir: _site

lang: pt

publish:
  method: gh-pages
  repo: FCopf/uc-probabilidade-estatistica

website:
  page-navigation: true
  title: "5290 - PROBABILIDADE E ESTATÍSTICA"
  description: "Página da UC 5290 - PE - Bict Mar - Unifesp"
  site-url: "https://fcopf.github.io/uc-probabilidade-estatistica"

  repo-url: "https://github.com/FCopf/uc-probabilidade-estatistica"
  open-graph: true

  page-footer:
    right: "BACHARELADO INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA DO MAR - Bict Mar - Unifesp"
    left: Fabio Cop Ferreira
    background: "#296354"

  sidebar: 
    background: "#3b8170"
    logo: "imagens/logo.png"
    style: "docked"
    search: true
    align: center
    tools:
      - icon: github
        href: https://github.com/FCopf/uc-probabilidade-estatistica
        text: GitHub da UC
      - icon: book
        href: https://moodlegrad.unifesp.br/
        text: Moodle Graduação
      - icon: terminal
        href: https://colab.research.google.com/drive/
        text: Google Colab
    
    collapse-level: 1
    contents:
      - section: "Informações do curso"
        contents:
          - href: informacoes_curso/plano_ensino.qmd
            text: Plano de ensino
          - href: index.qmd
            text: Cronograma
          - href: informacoes_curso/links_uteis.qmd
            text: Links úteis e Bibliografia
      - section: Material de apoio
        contents: 
          # - href: material_apoio/ideias_projeto.qmd
          #   text: "Ideias para o projeto final"
      - section: Leitura Obrigatória
        contents: 
          - href: https://fcopf.github.io/MEAD/conteudo/intro_bayes/intro-bayes-counting.html
            text: Semana 1
          - href: https://fcopf.github.io/MEAD/conteudo/intro_bayes/intro-bayes-distr-prob.html
            text: Semana 2  
      - section: Leitura Complementar
        contents: 
          - href: https://fcopf.github.io/MEAD/fundamentos_probabilidade.html
            text: Semana 1
          - href: https://fcopf.github.io/MEAD/conteudo/fundamentos_probabilidade/teorema_bayes.html
            text: Semana 2
      - section: Lab. Informática
        contents: 
          - href: lab-info/implementacao-aula-2.qmd
            text: Semana 2
          - href: https://fcopf.github.io/MEAD/conteudo/intro_bayes/intro-bayes-binomial-grid.html
            text: Semana 3
          - href: https://fcopf.github.io/MEAD/conteudo/intro_bayes/intro-bayes-binomial-pymc.html
            text: Semana 4
          - href: lab-info/modelo_normal_bayesiano_priori.qmd
            text: Semana 6
      - section: Slides
        contents: 
          - href: /slides/Introdução_inferencia_modelagem_probabilistica.pdf
            text: Semana 1
          - href: https://fcopf-dash-ocean-surface.share.connect.posit.cloud/
            text: Semana 3a
          - href: https://fcopf-binomial-bayesiana.share.connect.posit.cloud/
            text: Semana 3b
      - section: "Listas de Exercícios"
        contents:
          - href: listas_exercicios/instrucoes-listas.qmd
            text: "Instruções"
          - href: listas_exercicios/lista-exercicios-1.qmd
            text: "Lista 1"
          - href: listas_exercicios/lista-exercicios-2.qmd
            text: "Lista 2"
          # - href: listas_exercicios/lista-exercicios-3.qmd
          #   text: "Lista 3"
          # - href: listas_exercicios/lista-exercicios-4.qmd
          #   text: "Lista 4"
          # - href: listas_exercicios/lista-exercicios-5.qmd
          #   text: "Lista 5"
          
      - section: "Avaliações"
        contents:
          # - href: avaliacao/avaliacao-1.qmd
          #   text: "Avaliação 1"
          # - href: avaliacao/avaliacao-2.qmd
          #   text: "Avaliação 2"
          # - href: avaliacao/avaliacao-3-projeto
          #   text: "Projeto"

# Global format configuration
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

# Configura projeto para ser executado apenas localmente
execute:
  freeze: auto

bibliography: references.bib